apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - cilium-chart.yaml
  - longhorn-chart.yaml
  - ingress-nginx-chart.yaml
  - kgateway-crd-oci.yaml
  - kgatewawy-controller-oci.yaml
